version: '{build}-{branch}'
image: Visual Studio 2017

skip_commits:
  files:
    - '**/*.md'
    
build_script:
- pwsh: dotnet build -c Release

test_script:
- pwsh: dotnet test ./tests/Prometheus.Client.Tests -c Release --no-build

after_test:
- pwsh: .\pack.ps1

artifacts:
- path: '**\artifacts\nuget\*.nupkg'
  name: Nuget
- path: '**\artifacts\myget\*.nupkg'
  name: Myget
  
deploy:
- provider: NuGet
  api_key:
    secure: zRa2gcYSMh0ddc8hB61BbGf7Z3Zx0y106S4XIkOWPPAFg3DmNP4qt+9LEDgKXteO
  artifact: NuGet
  on:
    appveyor_repo_tag: true   
- provider: NuGet
  server: https://www.myget.org/F/phnx47-beta/api/v2/package
  api_key:
    secure: Smuwoi47XyX6b6x66VpPnnL96F3cl1nukALrFnZo1Oony38dzouByG7pnt6DX4HT
  symbol_server: https://www.myget.org/F/phnx47-beta/symbols/api/v2/package
  artifact: MyGet
  on:
    branch: 2.2
    appveyor_repo_tag: false
