name: ğŸ’¿ CI Branch

on:
  push:
    branches-ignore:
      - "master"

jobs:
  build-branch:
    name: ğŸ­ Build Branch
    runs-on: ubuntu-20.04
    steps:
      - name: ğŸšš Checkout
        uses: actions/checkout@master
      - name: ğŸ›  Setup .NET Core
        uses: actions/setup-dotnet@master
      - name: âš™ Restore
        run: dotnet restore
      - name: ğŸ­ Build
        run: dotnet build --no-restore -c Release
      - name: ğŸ§ª Tests
        run: dotnet test --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - name: â˜¢ Publish to Codecov
        uses: codecov/codecov-action@v1
