name: "master"

on:
  push:
    branches:
      - master
    tags:
      - '!refs/tags/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/PrometheusClientNet/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GH_DEPLOY_KEY}}
      - name: Build
        run: dotnet build -c Release
      - name: Tests
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - name: Pack
        run: dotnet pack src -c Release --no-build --version-suffix dev-$(date +%s) -o artifacts/
      - name: Publish to GitHub
        run: dotnet nuget push "artifacts/*.nupkg" --skip-duplicate --no-symbols true
