name: CI

on:
  push:
    branches:
      - 'master'
    tags:
      - '!refs/tags/*'

jobs:
  build-publish-dev:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Tests
        run: dotnet test --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - name: Publish to Codecov
        uses: codecov/codecov-action@v1
      - name: Pack artifacts
        run: | 
          dotnet pack src/Prometheus.Client -c Release --no-build --version-suffix dev-$(date +%s) -o artifacts/
          dotnet pack src/Prometheus.Client.Abstractions -c Release --no-build --version-suffix dev-$(date +%s) -o artifacts/
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nupkg
          path: artifacts/*
      - name: Publish to GitHub
        run: |
          dotnet tool install -g gpr --no-cache -v q
          gpr push "artifacts/*.nupkg" -k ${{ secrets.GH_DEPLOY_KEY }} || true   
