name: ğŸ’¿ CI Master

on:
  push:
    branches:
      - "master"

jobs:
  build-master:
    name: ğŸ­ Build Master
    runs-on: ubuntu-20.04
    steps:
      - name: ğŸšš Checkout
        uses: actions/checkout@v2
      - name: ğŸ›  Setup .NET Core
        uses: actions/setup-dotnet@v1
      - name: âš™ Restore
        run: dotnet restore
      - name: ğŸ­ Build
        run: dotnet build --no-restore -c Release /p:ContinuousIntegrationBuild=true
      - name: ğŸ§ª Run tests
        run: dotnet test --no-build -c Release --filter FullyQualifiedName\!~Tests.Integration /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - name: â˜¢ Publish to Codecov
        uses: codecov/codecov-action@v2
      - name: ğŸ—œ Pack artifacts
        run: dotnet pack --no-build -c Release --version-suffix dev-$(date +%s) -o artifacts/
      - name: ğŸ—„ Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nupkg
          path: artifacts/*
      - name: ğŸ“¦ Publish to GitHub
        run: dotnet nuget push "artifacts/*.nupkg" -s https://nuget.pkg.github.com/prom-client-net/index.json -k ${{ secrets.GH_DEPLOY_KEY }} --skip-duplicate
