name: ğŸ’¿ CI Prod

on:
  push:
    tags:
      - 'v*'

jobs:
  build-prod:
    name: ğŸ­ Build Prod
    runs-on: ubuntu-20.04
    steps:
      - name: ğŸšš Checkout
        uses: actions/checkout@master
      - name: ğŸ›  Setup .NET Core
        uses: actions/setup-dotnet@master
      - name: âš™ Restore
        run: dotnet restore
      - name: ğŸ­ Build
        run: dotnet build --no-restore -c Release
      - name: ğŸ§ª Tests
        run: dotnet test --no-build -c Release
      - name: ğŸ—œ Pack artifacts
        run: |
          dotnet pack src/Prometheus.Client -c Release --no-build --version-suffix dev-$(date +%s) -o artifacts/
          dotnet pack src/Prometheus.Client.Abstractions -c Release --no-build --version-suffix dev-$(date +%s) -o artifacts/
      - name: ğŸ—„ Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nupkg
          path: artifacts/*
      - name: ğŸ“¦ Publish to NuGet
        run: dotnet nuget push "artifacts/*.nupkg" --api-key ${{ secrets.NUGET_DEPLOY_KEY }} --source https://api.nuget.org/v3/index.json
