name: ğŸ’¿ CI Prod

on:
  push:
    tags:
      - "v*"

jobs:
  build-prod:
    name: ğŸ­ Build Prod
    runs-on: ubuntu-20.04
    steps:
      - name: ğŸšš Checkout
        uses: actions/checkout@v3
      - name: ğŸ›  Setup .NET Core
        uses: actions/setup-dotnet@v2
      - name: âš™ Restore
        run: dotnet restore
      - name: ğŸ­ Build
        run: dotnet build --no-restore -c Release /p:ContinuousIntegrationBuild=true
      - name: ğŸ§ª Run tests
        run: dotnet test --no-build -c Release --filter FullyQualifiedName\!~Tests.Integration /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - name: â˜¢ Publish to Codecov
        uses: codecov/codecov-action@v2
      - name: ğŸ—œ Pack artifacts
        run: dotnet pack -c Release --no-build -o artifacts/
      - name: ğŸ—„ Publish artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nupkg
          path: artifacts/*
      - name: ğŸ“¦ Publish to GitHub
        run: dotnet nuget push "artifacts/*.nupkg" -s https://nuget.pkg.github.com/prom-client-net/index.json -k ${{ secrets.GH_DEPLOY_KEY }} --skip-duplicate
      - name: ğŸ“¦ Publish to NuGet
        run: dotnet nuget push "artifacts/*.nupkg" -k ${{ secrets.NUGET_DEPLOY_KEY }} -s https://api.nuget.org/v3/index.json
